services:
    node:
        image: node:18
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        ports:
            - "5173:5173"
        command: sh -c "npm install && npm run dev"

    app:
        build: .
        volumes:
            - .:/var/www/html
        ports:
            - "8000:80"
        env_file:
            - .env
        depends_on:
            - db
    db:
        image: postgres:15
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: laravel
        ports:
            - "5432:5432"
        volumes:
            - dbdata:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        depends_on:
            - db
        volumes:
            - pgadmin-data:/var/lib/pgadmin

volumes:
    dbdata:
    pgadmin-data:
